//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int id { get; set; }
        public string RequiredExp { get; set; }
        public string Description { get; set; }
        public string Technology { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string JobOpening { get; set; }
        public string ShiftTiming { get; set; }
        public string JobTitle { get; set; }
        public string Shift { get; set; }
        public System.DateTime JobCreateDate { get; set; }
        public string SalaryRange { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> SkillId { get; set; }
        public Nullable<int> ExpYear { get; set; }
        public int CompanyId { get; set; }
    }
}
