//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JobsDBEntities : DbContext
    {
        public JobsDBEntities()
            : base("name=JobsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<City> Cities { get; set; }
    
        public virtual ObjectResult<getJobs_Result> getJobs(Nullable<int> cityId, Nullable<int> skillId, Nullable<int> expYear)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(int));
    
            var skillIdParameter = skillId.HasValue ?
                new ObjectParameter("SkillId", skillId) :
                new ObjectParameter("SkillId", typeof(int));
    
            var expYearParameter = expYear.HasValue ?
                new ObjectParameter("ExpYear", expYear) :
                new ObjectParameter("ExpYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getJobs_Result>("getJobs", cityIdParameter, skillIdParameter, expYearParameter);
        }
    }
}
